### ISSUE TITLE
getting 404 on deployment delete

### ISSUE THREAD

**Issue by PradeepSingh1988** [kubernetes-incubator/client-python#308]
#`Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 27 Jul 2017 09:15:13 GMT', 'Content-Length': '448', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.extensions \"{u'name': u'first-experiment-5fdc9f9b-f50b-41ae-a0bb-4d55af3a993f', u'uuid': u'09b7367f-72ac-11e7-b784-1803732bfee3'}\" not found","reason":"NotFound","details":{"name":"{u'name': u'first-experiment-5fdc9f9b-f50b-41ae-a0bb-4d55af3a993f', u'uuid': u'09b7367f-72ac-11e7-b784-1803732bfee3'}","group":"extensions","kind":"deployments"},"code":404}
`

```
class K8sClient(object):
    def __init__(self, config_file):
        config.load_kube_config(config_file=config_file)
        self.v1 = client.CoreV1Api()
        self.v1beta = client.ExtensionsV1beta1Api()
   def create_deployment(self, body):
        dep = yaml.load(body)
        resp = self.v1beta.create_namespaced_deployment(body=dep, namespace="default")
        return resp

   def delete_deployment(self, name):
        resp = self.v1beta.delete_namespaced_deployment(
            name, "default", client.V1DeleteOptions(grace_period_seconds=5))
        return resp
```

template is like below:
```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ name }}-{{ uuid }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ name }}-{{ uuid }}
    spec:
      containers:
      - name: {{ name }}-{{ uuid }}
        image: {{ image }}
        ports:
        - containerPort: {{ port }}
```
I am able to delete using kubectl. 
I am using kubernetes==2.0.0.
