### ISSUE TITLE
V1ConfigMapKeySelector missing name field?

### ISSUE THREAD

**Issue by lmccalman** [kubernetes-incubator/client-python#85]
I'm trying to give environment variables to a V1Container constructor, and particularly I want those environment variables to come from a config map. In yaml it would look like:

```
env:
  - name: MY_ENV_VAR
    valueFrom:
      configMapKeyRef:
          name: myconfigmap
          key: foo
```
However, the V1ConfigMapKeySelector that is expected in the constructor of V1EnvVarSource only takes a 'key' argument, not the 'name' argument.  Is this a change in the API or am I using the wrong types? My apologies if I've misunderstood! The same issue seems to apply to V1SecretKeySelector too.
