### ISSUE TITLE
How to create a NFS volume?

### ISSUE THREAD

**Issue by stibi** [kubernetes-incubator/client-python#86]
Hello,

I'm creating deployments with a NFS volume like this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  ...
  labels:
    ...
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        ...
      spec:
      containers:
      - image: ...
        name: ...
        imagePullPolicy: Always
        env:
        - name: foo
          value: "bar"
        ports:
        - containerPort: 80
          name: foobar
        volumeMounts:
        - mountPath: /var/www/foo
          name: foo-mount
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
      volumes:
      - name: foo-mount
        nfs:
          path: /opt/nfs/foo
          server: 10.1.0.123
```

Is this possible the python kubernetes client? The [V1Volume](https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/docs/V1Volume.md) don't specify the needed parameters, like the "nfs" option.

The k8s API definition for `V1Volume` mention several possible options, including NFS: http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1_volume

There is also the `v1.NFSVolumeSource`: http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1_nfsvolumesource

If this is not implemented yet, can I help somehow?
